import { supabase } from "@/integrations/supabase/client";

// ─── Default tasks auto-created for every new case ────────────────────────────
const DEFAULT_TASKS = [
  { task_title: "Call patient to confirm case details",    priority: "high",   sort_order: 1 },
  { task_title: "Collect medical reports & documents",     priority: "high",   sort_order: 2 },
  { task_title: "Share hospital options with patient",     priority: "medium", sort_order: 3 },
  { task_title: "Schedule consultation",                   priority: "high",   sort_order: 4 },
  { task_title: "Confirm admission date",                  priority: "medium", sort_order: 5 },
  { task_title: "Confirm procedure date",                  priority: "medium", sort_order: 6 },
  { task_title: "Post-discharge follow-up call",           priority: "medium", sort_order: 7 },
  { task_title: "Collect patient review / feedback",       priority: "low",    sort_order: 8 },
];

// ─── Timeline ─────────────────────────────────────────────────────────────────
export async function addTimelineEntry(
  caseId: string,
  actionType: string,
  description: string,
  performedBy: string,
  metadata?: Record<string, any>
) {
  const { error } = await supabase.from("case_timeline").insert({
    case_id: caseId,
    action_type: actionType,
    description,
    performed_by: performedBy,
    metadata: metadata ?? {},
  });
  if (error) throw error;
}

// ─── Convert Lead → Case ──────────────────────────────────────────────────────
export interface LeadForConversion {
  id: string;
  name: string;
  phone?: string;
  email?: string;
  city?: string;
  procedure_interest?: string;
}

export async function convertLeadToCase(
  lead: LeadForConversion,
  coordinatorId: string,
  specialtyId?: string
): Promise<{ caseId: string; caseCode: string }> {

  // ── Dedup: return existing case if this lead was already converted ─────────
  const { data: existing } = await supabase
    .from("patient_cases")
    .select("id, case_code")
    .eq("lead_id", lead.id)
    .maybeSingle();

  if (existing) {
    return { caseId: existing.id, caseCode: existing.case_code ?? "" };
  }

  // Insert case — case_code is auto-generated by DB trigger
  const { data: newCase, error: caseErr } = await supabase
    .from("patient_cases")
    .insert({
      title: `${lead.procedure_interest || "Enquiry"} — ${lead.name}`,
      description: `Case converted from lead. Patient: ${lead.name}${lead.phone ? `, Phone: ${lead.phone}` : ""}${lead.city ? `, City: ${lead.city}` : ""}.`,
      specialty_id: specialtyId ?? null,
      coordinator_id: coordinatorId,
      lead_id: lead.id,
      case_stage: "case_created",
      priority: "medium",
      status: "new",
      patient_id: coordinatorId, // placeholder — updated once patient has an account
    })
    .select("id, case_code")
    .single();

  if (caseErr) throw caseErr;

  const caseId   = newCase.id;
  const caseCode = newCase.case_code ?? "";

  // Mark lead as converted
  await supabase
    .from("leads")
    .update({
      crm_status: "converted",
      qualification_status: "qualified",
      converted_at: new Date().toISOString(),
    })
    .eq("id", lead.id);

  // Create default tasks
  await supabase.from("case_tasks").insert(
    DEFAULT_TASKS.map((t) => ({ ...t, case_id: caseId, assigned_to: coordinatorId }))
  );

  // Initial timeline entry
  await addTimelineEntry(
    caseId,
    "case_created",
    `Case created from lead ${lead.id}. Patient: ${lead.name}.`,
    coordinatorId,
    { lead_id: lead.id, case_code: caseCode }
  );

  return { caseId, caseCode };
}

// ─── Assign Hospital / Doctor ─────────────────────────────────────────────────
export async function assignCase(
  caseId: string,
  assignments: { hospitalId?: string | null; doctorId?: string | null },
  performedBy: string,
  hospitalName?: string,
  doctorName?: string
) {
  const updates: Record<string, any> = { case_stage: "assigned" };
  if (assignments.hospitalId !== undefined) updates.hospital_id = assignments.hospitalId;
  if (assignments.doctorId   !== undefined) updates.doctor_id   = assignments.doctorId;

  const { error } = await supabase.from("patient_cases").update(updates).eq("id", caseId);
  if (error) throw error;

  if (assignments.hospitalId) {
    await addTimelineEntry(
      caseId, "hospital_assigned",
      `Hospital assigned: ${hospitalName ?? assignments.hospitalId}`,
      performedBy, { hospital_id: assignments.hospitalId }
    );
  }
  if (assignments.doctorId) {
    await addTimelineEntry(
      caseId, "doctor_assigned",
      `Doctor assigned: ${doctorName ?? assignments.doctorId}`,
      performedBy, { doctor_id: assignments.doctorId }
    );
  }
}

// ─── Update Case Stage ────────────────────────────────────────────────────────
export async function updateCaseStage(
  caseId: string,
  stage: string,
  performedBy: string,
  notes?: string
) {
  const { error } = await supabase
    .from("patient_cases")
    .update({ case_stage: stage })
    .eq("id", caseId);
  if (error) throw error;

  await addTimelineEntry(
    caseId, "stage_changed",
    `Stage updated to: ${stage.replace(/_/g, " ")}${notes ? ` — ${notes}` : ""}`,
    performedBy, { new_stage: stage }
  );
}

// ─── Update Task Status ───────────────────────────────────────────────────────
export async function updateTaskStatus(taskId: string, status: string) {
  const { error } = await supabase
    .from("case_tasks")
    .update({ status, updated_at: new Date().toISOString() })
    .eq("id", taskId);
  if (error) throw error;
}
