// This file is automatically generated. Do not edit it directly.
// Regenerate after schema changes with the Supabase MCP generate_typescript_types tool.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.4"
  }
  public: {
    Tables: {
      analytics_events: {
        Row: {
          browser: string | null
          created_at: string
          device_type: string | null
          event_name: string
          id: string
          landing_page: string | null
          page_path: string | null
          properties: Json
          referrer: string | null
          session_id: string | null
          utm_campaign: string | null
          utm_content: string | null
          utm_medium: string | null
          utm_source: string | null
          utm_term: string | null
        }
        Insert: {
          browser?: string | null
          created_at?: string
          device_type?: string | null
          event_name: string
          id?: string
          landing_page?: string | null
          page_path?: string | null
          properties?: Json
          referrer?: string | null
          session_id?: string | null
          utm_campaign?: string | null
          utm_content?: string | null
          utm_medium?: string | null
          utm_source?: string | null
          utm_term?: string | null
        }
        Update: {
          browser?: string | null
          created_at?: string
          device_type?: string | null
          event_name?: string
          id?: string
          landing_page?: string | null
          page_path?: string | null
          properties?: Json
          referrer?: string | null
          session_id?: string | null
          utm_campaign?: string | null
          utm_content?: string | null
          utm_medium?: string | null
          utm_source?: string | null
          utm_term?: string | null
        }
        Relationships: []
      }
      appointments: {
        Row: {
          appointment_type: string
          case_id: string
          created_at: string
          created_by: string | null
          doctor_id: string | null
          duration_minutes: number
          hospital_id: string | null
          id: string
          notes: string | null
          scheduled_at: string
          status: string
          updated_at: string
        }
        Insert: {
          appointment_type?: string
          case_id: string
          created_at?: string
          created_by?: string | null
          doctor_id?: string | null
          duration_minutes?: number
          hospital_id?: string | null
          id?: string
          notes?: string | null
          scheduled_at: string
          status?: string
          updated_at?: string
        }
        Update: {
          appointment_type?: string
          case_id?: string
          created_at?: string
          created_by?: string | null
          doctor_id?: string | null
          duration_minutes?: number
          hospital_id?: string | null
          id?: string
          notes?: string | null
          scheduled_at?: string
          status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "appointments_case_id_fkey"
            columns: ["case_id"]
            isOneToOne: false
            referencedRelation: "patient_cases"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "appointments_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "appointments_doctor_id_fkey"
            columns: ["doctor_id"]
            isOneToOne: false
            referencedRelation: "doctors"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "appointments_hospital_id_fkey"
            columns: ["hospital_id"]
            isOneToOne: false
            referencedRelation: "locations"
            referencedColumns: ["id"]
          },
        ]
      }
      areas: {
        Row: {
          city_id: string
          created_at: string
          id: string
          name: string
        }
        Insert: {
          city_id: string
          created_at?: string
          id?: string
          name: string
        }
        Update: {
          city_id?: string
          created_at?: string
          id?: string
          name?: string
        }
        Relationships: [
          {
            foreignKeyName: "areas_city_id_fkey"
            columns: ["city_id"]
            isOneToOne: false
            referencedRelation: "cities"
            referencedColumns: ["id"]
          },
        ]
      }
      audit_logs: {
        Row: {
          action: string
          actor_id: string | null
          created_at: string
          entity_id: string | null
          entity_type: string
          id: string
          new_data: Json | null
          old_data: Json | null
        }
        Insert: {
          action: string
          actor_id?: string | null
          created_at?: string
          entity_id?: string | null
          entity_type: string
          id?: string
          new_data?: Json | null
          old_data?: Json | null
        }
        Update: {
          action?: string
          actor_id?: string | null
          created_at?: string
          entity_id?: string | null
          entity_type?: string
          id?: string
          new_data?: Json | null
          old_data?: Json | null
        }
        Relationships: []
      }
      case_billing: {
        Row: {
          amount: number
          billing_title: string | null
          billing_type: string
          case_id: string
          created_at: string
          created_by: string | null
          currency: string
          description: string
          due_date: string | null
          id: string
          invoice_number: string | null
          notes: string | null
          paid_at: string | null
          payment_method: string | null
          payment_proof_path: string | null
          payment_reference: string | null
          status: string
          updated_at: string
        }
        Insert: {
          amount?: number
          billing_title?: string | null
          billing_type?: string
          case_id: string
          created_at?: string
          created_by?: string | null
          currency?: string
          description: string
          due_date?: string | null
          id?: string
          invoice_number?: string | null
          notes?: string | null
          paid_at?: string | null
          payment_method?: string | null
          payment_proof_path?: string | null
          payment_reference?: string | null
          status?: string
          updated_at?: string
        }
        Update: {
          amount?: number
          billing_title?: string | null
          billing_type?: string
          case_id?: string
          created_at?: string
          created_by?: string | null
          currency?: string
          description?: string
          due_date?: string | null
          id?: string
          invoice_number?: string | null
          notes?: string | null
          paid_at?: string | null
          payment_method?: string | null
          payment_proof_path?: string | null
          payment_reference?: string | null
          status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "case_billing_case_id_fkey"
            columns: ["case_id"]
            isOneToOne: false
            referencedRelation: "patient_cases"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "case_billing_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      case_documents: {
        Row: {
          case_id: string
          created_at: string | null
          document_type: string | null
          file_name: string
          file_path: string
          file_size: number | null
          file_type: string | null
          id: string
          is_verified: boolean
          mime_type: string | null
          notes: string | null
          uploaded_by: string
          verified_at: string | null
          verified_by: string | null
        }
        Insert: {
          case_id: string
          created_at?: string | null
          document_type?: string | null
          file_name: string
          file_path: string
          file_size?: number | null
          file_type?: string | null
          id?: string
          is_verified?: boolean
          mime_type?: string | null
          notes?: string | null
          uploaded_by: string
          verified_at?: string | null
          verified_by?: string | null
        }
        Update: {
          case_id?: string
          created_at?: string | null
          document_type?: string | null
          file_name?: string
          file_path?: string
          file_size?: number | null
          file_type?: string | null
          id?: string
          is_verified?: boolean
          mime_type?: string | null
          notes?: string | null
          uploaded_by?: string
          verified_at?: string | null
          verified_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "case_documents_case_id_fkey"
            columns: ["case_id"]
            isOneToOne: false
            referencedRelation: "patient_cases"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "case_documents_verified_by_fkey"
            columns: ["verified_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      case_invoices: {
        Row: {
          amount: number
          case_id: string
          created_at: string | null
          currency: string | null
          due_date: string | null
          id: string
          invoice_number: string
          issued_by: string | null
          notes: string | null
          paid_at: string | null
          status: string | null
        }
        Insert: {
          amount: number
          case_id: string
          created_at?: string | null
          currency?: string | null
          due_date?: string | null
          id?: string
          invoice_number: string
          issued_by?: string | null
          notes?: string | null
          paid_at?: string | null
          status?: string | null
        }
        Update: {
          amount?: number
          case_id?: string
          created_at?: string | null
          currency?: string | null
          due_date?: string | null
          id?: string
          invoice_number?: string
          issued_by?: string | null
          notes?: string | null
          paid_at?: string | null
          status?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "case_invoices_case_id_fkey"
            columns: ["case_id"]
            isOneToOne: false
            referencedRelation: "patient_cases"
            referencedColumns: ["id"]
          },
        ]
      }
      case_note_replies: {
        Row: {
          author_id: string | null
          author_role: string | null
          content: string
          created_at: string
          id: string
          note_id: string
        }
        Insert: {
          author_id?: string | null
          author_role?: string | null
          content: string
          created_at?: string
          id?: string
          note_id: string
        }
        Update: {
          author_id?: string | null
          author_role?: string | null
          content?: string
          created_at?: string
          id?: string
          note_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "case_note_replies_author_id_fkey"
            columns: ["author_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "case_note_replies_note_id_fkey"
            columns: ["note_id"]
            isOneToOne: false
            referencedRelation: "case_notes"
            referencedColumns: ["id"]
          },
        ]
      }
      case_notes: {
        Row: {
          author_id: string
          author_role: string | null
          case_id: string
          content: string
          created_at: string | null
          id: string
          is_internal: boolean | null
        }
        Insert: {
          author_id: string
          author_role?: string | null
          case_id: string
          content: string
          created_at?: string | null
          id?: string
          is_internal?: boolean | null
        }
        Update: {
          author_id?: string
          author_role?: string | null
          case_id?: string
          content?: string
          created_at?: string | null
          id?: string
          is_internal?: boolean | null
        }
        Relationships: [
          {
            foreignKeyName: "case_notes_author_id_profiles_fkey"
            columns: ["author_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "case_notes_case_id_fkey"
            columns: ["case_id"]
            isOneToOne: false
            referencedRelation: "patient_cases"
            referencedColumns: ["id"]
          },
        ]
      }
      case_notifications: {
        Row: {
          body: string | null
          case_id: string | null
          created_at: string | null
          id: string
          is_read: boolean | null
          title: string
          type: string | null
          user_id: string
        }
        Insert: {
          body?: string | null
          case_id?: string | null
          created_at?: string | null
          id?: string
          is_read?: boolean | null
          title: string
          type?: string | null
          user_id: string
        }
        Update: {
          body?: string | null
          case_id?: string | null
          created_at?: string | null
          id?: string
          is_read?: boolean | null
          title?: string
          type?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "case_notifications_case_id_fkey"
            columns: ["case_id"]
            isOneToOne: false
            referencedRelation: "patient_cases"
            referencedColumns: ["id"]
          },
        ]
      }
      case_status_history: {
        Row: {
          case_id: string
          changed_by: string | null
          created_at: string | null
          id: string
          notes: string | null
          status: Database["public"]["Enums"]["case_status"]
        }
        Insert: {
          case_id: string
          changed_by?: string | null
          created_at?: string | null
          id?: string
          notes?: string | null
          status: Database["public"]["Enums"]["case_status"]
        }
        Update: {
          case_id?: string
          changed_by?: string | null
          created_at?: string | null
          id?: string
          notes?: string | null
          status?: Database["public"]["Enums"]["case_status"]
        }
        Relationships: [
          {
            foreignKeyName: "case_status_history_case_id_fkey"
            columns: ["case_id"]
            isOneToOne: false
            referencedRelation: "patient_cases"
            referencedColumns: ["id"]
          },
        ]
      }
      case_tasks: {
        Row: {
          assigned_to: string | null
          case_id: string
          completed_at: string | null
          created_at: string
          created_by: string | null
          due_date: string | null
          id: string
          notes: string | null
          priority: string
          sort_order: number
          status: string
          task_title: string
          updated_at: string
        }
        Insert: {
          assigned_to?: string | null
          case_id: string
          completed_at?: string | null
          created_at?: string
          created_by?: string | null
          due_date?: string | null
          id?: string
          notes?: string | null
          priority?: string
          sort_order?: number
          status?: string
          task_title: string
          updated_at?: string
        }
        Update: {
          assigned_to?: string | null
          case_id?: string
          completed_at?: string | null
          created_at?: string
          created_by?: string | null
          due_date?: string | null
          id?: string
          notes?: string | null
          priority?: string
          sort_order?: number
          status?: string
          task_title?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "case_tasks_assigned_to_fkey"
            columns: ["assigned_to"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "case_tasks_case_id_fkey"
            columns: ["case_id"]
            isOneToOne: false
            referencedRelation: "patient_cases"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "case_tasks_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      case_timeline: {
        Row: {
          action_type: string
          case_id: string
          created_at: string
          description: string | null
          id: string
          metadata: Json
          performed_by: string | null
        }
        Insert: {
          action_type: string
          case_id: string
          created_at?: string
          description?: string | null
          id?: string
          metadata?: Json
          performed_by?: string | null
        }
        Update: {
          action_type?: string
          case_id?: string
          created_at?: string
          description?: string | null
          id?: string
          metadata?: Json
          performed_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "case_timeline_case_id_fkey"
            columns: ["case_id"]
            isOneToOne: false
            referencedRelation: "patient_cases"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "case_timeline_performed_by_fkey"
            columns: ["performed_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      cities: {
        Row: {
          country_id: string | null
          created_at: string
          id: string
          is_featured: boolean
          name: string
          slug: string
          state_id: string | null
        }
        Insert: {
          country_id?: string | null
          created_at?: string
          id?: string
          is_featured?: boolean
          name: string
          slug: string
          state_id?: string | null
        }
        Update: {
          country_id?: string | null
          created_at?: string
          id?: string
          is_featured?: boolean
          name?: string
          slug?: string
          state_id?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "cities_country_id_fkey"
            columns: ["country_id"]
            isOneToOne: false
            referencedRelation: "countries"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "cities_state_id_fkey"
            columns: ["state_id"]
            isOneToOne: false
            referencedRelation: "states"
            referencedColumns: ["id"]
          },
        ]
      }
      conversation_participants: {
        Row: {
          conversation_id: string
          id: string
          joined_at: string | null
          user_id: string
        }
        Insert: {
          conversation_id: string
          id?: string
          joined_at?: string | null
          user_id: string
        }
        Update: {
          conversation_id?: string
          id?: string
          joined_at?: string | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "conversation_participants_conversation_id_fkey"
            columns: ["conversation_id"]
            isOneToOne: false
            referencedRelation: "conversations"
            referencedColumns: ["id"]
          },
        ]
      }
      conversations: {
        Row: {
          case_id: string | null
          created_at: string | null
          id: string
          title: string | null
        }
        Insert: {
          case_id?: string | null
          created_at?: string | null
          id?: string
          title?: string | null
        }
        Update: {
          case_id?: string | null
          created_at?: string | null
          id?: string
          title?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "conversations_case_id_fkey"
            columns: ["case_id"]
            isOneToOne: false
            referencedRelation: "patient_cases"
            referencedColumns: ["id"]
          },
        ]
      }
      countries: {
        Row: {
          code: string | null
          created_at: string
          id: string
          name: string
        }
        Insert: {
          code?: string | null
          created_at?: string
          id?: string
          name: string
        }
        Update: {
          code?: string | null
          created_at?: string
          id?: string
          name?: string
        }
        Relationships: []
      }
      doctor_reviews: {
        Row: {
          area: string
          created_at: string
          doctor_id: string
          id: string
          image_url: string | null
          name: string
          quote: string
          rating: number
        }
        Insert: {
          area: string
          created_at?: string
          doctor_id: string
          id?: string
          image_url?: string | null
          name: string
          quote: string
          rating?: number
        }
        Update: {
          area?: string
          created_at?: string
          doctor_id?: string
          id?: string
          image_url?: string | null
          name?: string
          quote?: string
          rating?: number
        }
        Relationships: [
          {
            foreignKeyName: "doctor_reviews_doctor_id_fkey"
            columns: ["doctor_id"]
            isOneToOne: false
            referencedRelation: "doctors"
            referencedColumns: ["id"]
          },
        ]
      }
      doctors: {
        Row: {
          bio: string
          change_request_notes: string[] | null
          cities: string[]
          consultation_fee: string
          created_at: string
          designation: string
          documents: Json | null
          experience: string
          hospital_id: string | null
          hospitals: string[]
          id: string
          image_url: string | null
          is_active: boolean | null
          is_published: boolean | null
          languages: string[]
          medical_reg_number: string | null
          name: string
          qualifications: string[]
          rejection_reason: string | null
          slug: string
          specializations: string[]
          status: Database["public"]["Enums"]["verification_status"] | null
          submitted_at: string | null
          surgeries: string[]
          user_id: string | null
          verified_at: string | null
          verified_by: string | null
        }
        Insert: {
          bio?: string
          change_request_notes?: string[] | null
          cities?: string[]
          consultation_fee?: string
          created_at?: string
          designation: string
          documents?: Json | null
          experience: string
          hospital_id?: string | null
          hospitals?: string[]
          id?: string
          image_url?: string | null
          is_active?: boolean | null
          is_published?: boolean | null
          languages?: string[]
          medical_reg_number?: string | null
          name: string
          qualifications?: string[]
          rejection_reason?: string | null
          slug: string
          specializations?: string[]
          status?: Database["public"]["Enums"]["verification_status"] | null
          submitted_at?: string | null
          surgeries?: string[]
          user_id?: string | null
          verified_at?: string | null
          verified_by?: string | null
        }
        Update: {
          bio?: string
          change_request_notes?: string[] | null
          cities?: string[]
          consultation_fee?: string
          created_at?: string
          designation?: string
          documents?: Json | null
          experience?: string
          hospital_id?: string | null
          hospitals?: string[]
          id?: string
          image_url?: string | null
          is_active?: boolean | null
          is_published?: boolean | null
          languages?: string[]
          medical_reg_number?: string | null
          name?: string
          qualifications?: string[]
          rejection_reason?: string | null
          slug?: string
          specializations?: string[]
          status?: Database["public"]["Enums"]["verification_status"] | null
          submitted_at?: string | null
          surgeries?: string[]
          user_id?: string | null
          verified_at?: string | null
          verified_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "doctors_hospital_id_fkey"
            columns: ["hospital_id"]
            isOneToOne: false
            referencedRelation: "hospitals"
            referencedColumns: ["id"]
          },
        ]
      }
      fertility_package_testimonials: {
        Row: {
          age: number | null
          consent_given: boolean
          created_at: string
          display_name: string
          display_order: number
          id: string
          is_approved: boolean
          journey: string | null
          package_id: string
          quote: string
          rating: number
        }
        Insert: {
          age?: number | null
          consent_given?: boolean
          created_at?: string
          display_name: string
          display_order?: number
          id?: string
          is_approved?: boolean
          journey?: string | null
          package_id: string
          quote: string
          rating?: number
        }
        Update: {
          age?: number | null
          consent_given?: boolean
          created_at?: string
          display_name?: string
          display_order?: number
          id?: string
          is_approved?: boolean
          journey?: string | null
          package_id?: string
          quote?: string
          rating?: number
        }
        Relationships: [
          {
            foreignKeyName: "fertility_package_testimonials_package_id_fkey"
            columns: ["package_id"]
            isOneToOne: false
            referencedRelation: "fertility_packages"
            referencedColumns: ["id"]
          },
        ]
      }
      fertility_packages: {
        Row: {
          audience: string
          availability_type: string
          badge: string | null
          category: string
          compare_at_price: number | null
          comparison: Json
          content_status: string
          created_at: string
          currency: string
          discount_label: string | null
          display_order: number
          duration: string | null
          exclusions: string[]
          faqs: Json
          featured: boolean
          hero_description: string
          hero_title: string
          how_it_works: Json
          icon: string
          id: string
          ideal_for: Json
          ideal_for_label: string
          inclusions: Json
          intents: string[]
          locations: string[]
          long_description: string
          name: string
          price: number | null
          price_placeholder_label: string
          price_status: string
          seo: Json
          short_description: string
          slug: string
          status: string
          tagline: string
          updated_at: string
          variants: Json
          what_you_learn: string[]
        }
        Insert: {
          audience?: string
          availability_type?: string
          badge?: string | null
          category?: string
          compare_at_price?: number | null
          comparison?: Json
          content_status?: string
          created_at?: string
          currency?: string
          discount_label?: string | null
          display_order?: number
          duration?: string | null
          exclusions?: string[]
          faqs?: Json
          featured?: boolean
          hero_description?: string
          hero_title?: string
          how_it_works?: Json
          icon?: string
          id?: string
          ideal_for?: Json
          ideal_for_label?: string
          inclusions?: Json
          intents?: string[]
          locations?: string[]
          long_description?: string
          name: string
          price?: number | null
          price_placeholder_label?: string
          price_status?: string
          seo?: Json
          short_description?: string
          slug: string
          status?: string
          tagline?: string
          updated_at?: string
          variants?: Json
          what_you_learn?: string[]
        }
        Update: {
          audience?: string
          availability_type?: string
          badge?: string | null
          category?: string
          compare_at_price?: number | null
          comparison?: Json
          content_status?: string
          created_at?: string
          currency?: string
          discount_label?: string | null
          display_order?: number
          duration?: string | null
          exclusions?: string[]
          faqs?: Json
          featured?: boolean
          hero_description?: string
          hero_title?: string
          how_it_works?: Json
          icon?: string
          id?: string
          ideal_for?: Json
          ideal_for_label?: string
          inclusions?: Json
          intents?: string[]
          locations?: string[]
          long_description?: string
          name?: string
          price?: number | null
          price_placeholder_label?: string
          price_status?: string
          seo?: Json
          short_description?: string
          slug?: string
          status?: string
          tagline?: string
          updated_at?: string
          variants?: Json
          what_you_learn?: string[]
        }
        Relationships: []
      }
      hospital_members: {
        Row: {
          created_at: string | null
          hospital_id: string
          id: string
          is_active: boolean | null
          member_role: string
          user_id: string
        }
        Insert: {
          created_at?: string | null
          hospital_id: string
          id?: string
          is_active?: boolean | null
          member_role?: string
          user_id: string
        }
        Update: {
          created_at?: string | null
          hospital_id?: string
          id?: string
          is_active?: boolean | null
          member_role?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "hospital_members_hospital_id_fkey"
            columns: ["hospital_id"]
            isOneToOne: false
            referencedRelation: "locations"
            referencedColumns: ["id"]
          },
        ]
      }
      hospitals: {
        Row: {
          address: string | null
          city: string | null
          created_at: string | null
          email: string | null
          id: string
          is_active: boolean | null
          logo_url: string | null
          name: string
          phone: string | null
          slug: string
          updated_at: string | null
        }
        Insert: {
          address?: string | null
          city?: string | null
          created_at?: string | null
          email?: string | null
          id?: string
          is_active?: boolean | null
          logo_url?: string | null
          name: string
          phone?: string | null
          slug: string
          updated_at?: string | null
        }
        Update: {
          address?: string | null
          city?: string | null
          created_at?: string | null
          email?: string | null
          id?: string
          is_active?: boolean | null
          logo_url?: string | null
          name?: string
          phone?: string | null
          slug?: string
          updated_at?: string | null
        }
        Relationships: []
      }
      leads: {
        Row: {
          age: number | null
          assigned_coordinator_id: string | null
          assigned_to: string | null
          browser: string | null
          city: string
          consent_given: boolean
          consent_given_at: string | null
          consultation_preference: string | null
          converted_at: string | null
          created_at: string
          crm_status: string
          device_type: string | null
          email: string | null
          first_touch_campaign: string | null
          first_touch_medium: string | null
          first_touch_source: string | null
          follow_up_date: string | null
          gender: string | null
          id: string
          landing_page: string | null
          last_touch_campaign: string | null
          last_touch_medium: string | null
          last_touch_source: string | null
          lead_code: string | null
          lead_type: string
          name: string
          notes: string | null
          package_name: string | null
          package_slug: string | null
          package_variant: string | null
          partner_name: string | null
          partner_phone: string | null
          phone: string
          preferred_city: string | null
          preferred_date: string | null
          preferred_time: string | null
          priority: string
          procedure_interest: string
          qualification_status: string
          referrer: string | null
          source_page: string | null
          updated_at: string | null
          utm_campaign: string | null
          utm_content: string | null
          utm_medium: string | null
          utm_source: string | null
          utm_term: string | null
        }
        Insert: {
          age?: number | null
          assigned_coordinator_id?: string | null
          assigned_to?: string | null
          browser?: string | null
          city: string
          consent_given?: boolean
          consent_given_at?: string | null
          consultation_preference?: string | null
          converted_at?: string | null
          created_at?: string
          crm_status?: string
          device_type?: string | null
          email?: string | null
          first_touch_campaign?: string | null
          first_touch_medium?: string | null
          first_touch_source?: string | null
          follow_up_date?: string | null
          gender?: string | null
          id?: string
          landing_page?: string | null
          last_touch_campaign?: string | null
          last_touch_medium?: string | null
          last_touch_source?: string | null
          lead_code?: string | null
          lead_type?: string
          name: string
          notes?: string | null
          package_name?: string | null
          package_slug?: string | null
          package_variant?: string | null
          partner_name?: string | null
          partner_phone?: string | null
          phone: string
          preferred_city?: string | null
          preferred_date?: string | null
          preferred_time?: string | null
          priority?: string
          procedure_interest: string
          qualification_status?: string
          referrer?: string | null
          source_page?: string | null
          updated_at?: string | null
          utm_campaign?: string | null
          utm_content?: string | null
          utm_medium?: string | null
          utm_source?: string | null
          utm_term?: string | null
        }
        Update: {
          age?: number | null
          assigned_coordinator_id?: string | null
          assigned_to?: string | null
          browser?: string | null
          city?: string
          consent_given?: boolean
          consent_given_at?: string | null
          consultation_preference?: string | null
          converted_at?: string | null
          created_at?: string
          crm_status?: string
          device_type?: string | null
          email?: string | null
          first_touch_campaign?: string | null
          first_touch_medium?: string | null
          first_touch_source?: string | null
          follow_up_date?: string | null
          gender?: string | null
          id?: string
          landing_page?: string | null
          last_touch_campaign?: string | null
          last_touch_medium?: string | null
          last_touch_source?: string | null
          lead_code?: string | null
          lead_type?: string
          name?: string
          notes?: string | null
          package_name?: string | null
          package_slug?: string | null
          package_variant?: string | null
          partner_name?: string | null
          partner_phone?: string | null
          phone?: string
          preferred_city?: string | null
          preferred_date?: string | null
          preferred_time?: string | null
          priority?: string
          procedure_interest?: string
          qualification_status?: string
          referrer?: string | null
          source_page?: string | null
          updated_at?: string | null
          utm_campaign?: string | null
          utm_content?: string | null
          utm_medium?: string | null
          utm_source?: string | null
          utm_term?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "leads_assigned_coordinator_id_fkey"
            columns: ["assigned_coordinator_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      locations: {
        Row: {
          areas: string[]
          change_request_notes: string[] | null
          city_id: string
          contact_person: string | null
          created_at: string
          documents: Json | null
          id: string
          is_active: boolean | null
          is_published: boolean | null
          license_number: string | null
          name: string
          rejection_reason: string | null
          status: Database["public"]["Enums"]["verification_status"] | null
          submitted_at: string | null
          surgeries: string[]
          user_id: string | null
          verified_at: string | null
          verified_by: string | null
        }
        Insert: {
          areas?: string[]
          change_request_notes?: string[] | null
          city_id: string
          contact_person?: string | null
          created_at?: string
          documents?: Json | null
          id?: string
          is_active?: boolean | null
          is_published?: boolean | null
          license_number?: string | null
          name: string
          rejection_reason?: string | null
          status?: Database["public"]["Enums"]["verification_status"] | null
          submitted_at?: string | null
          surgeries?: string[]
          user_id?: string | null
          verified_at?: string | null
          verified_by?: string | null
        }
        Update: {
          areas?: string[]
          change_request_notes?: string[] | null
          city_id?: string
          contact_person?: string | null
          created_at?: string
          documents?: Json | null
          id?: string
          is_active?: boolean | null
          is_published?: boolean | null
          license_number?: string | null
          name?: string
          rejection_reason?: string | null
          status?: Database["public"]["Enums"]["verification_status"] | null
          submitted_at?: string | null
          surgeries?: string[]
          user_id?: string | null
          verified_at?: string | null
          verified_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "locations_city_id_fkey"
            columns: ["city_id"]
            isOneToOne: false
            referencedRelation: "cities"
            referencedColumns: ["id"]
          },
        ]
      }
      messages: {
        Row: {
          content: string
          conversation_id: string
          created_at: string | null
          id: string
          is_read: boolean | null
          sender_id: string
        }
        Insert: {
          content: string
          conversation_id: string
          created_at?: string | null
          id?: string
          is_read?: boolean | null
          sender_id: string
        }
        Update: {
          content?: string
          conversation_id?: string
          created_at?: string | null
          id?: string
          is_read?: boolean | null
          sender_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "messages_conversation_id_fkey"
            columns: ["conversation_id"]
            isOneToOne: false
            referencedRelation: "conversations"
            referencedColumns: ["id"]
          },
        ]
      }
      notifications: {
        Row: {
          body: string | null
          created_at: string
          id: string
          is_read: boolean
          reference_id: string | null
          reference_type: string | null
          title: string
          type: string
          user_id: string
        }
        Insert: {
          body?: string | null
          created_at?: string
          id?: string
          is_read?: boolean
          reference_id?: string | null
          reference_type?: string | null
          title: string
          type?: string
          user_id: string
        }
        Update: {
          body?: string | null
          created_at?: string
          id?: string
          is_read?: boolean
          reference_id?: string | null
          reference_type?: string | null
          title?: string
          type?: string
          user_id?: string
        }
        Relationships: []
      }
      package_reviews: {
        Row: {
          city: string
          created_at: string
          id: string
          name: string
          package_id: string
          rating: number
          text: string
        }
        Insert: {
          city: string
          created_at?: string
          id?: string
          name: string
          package_id: string
          rating?: number
          text: string
        }
        Update: {
          city?: string
          created_at?: string
          id?: string
          name?: string
          package_id?: string
          rating?: number
          text?: string
        }
        Relationships: [
          {
            foreignKeyName: "package_reviews_package_id_fkey"
            columns: ["package_id"]
            isOneToOne: false
            referencedRelation: "packages"
            referencedColumns: ["id"]
          },
        ]
      }
      packages: {
        Row: {
          available_hospitals: string[] | null
          avg_rating: number
          cities: string[]
          created_at: string
          description: string
          duration: string | null
          features: string[] | null
          icon_name: string
          id: string
          includes: string[]
          is_published: boolean
          overview: string | null
          price: string
          recovery: string | null
          slug: string
          specialty_id: string | null
          success_rate: string | null
          tag: string | null
          title: string
          total_patients: string | null
        }
        Insert: {
          available_hospitals?: string[] | null
          avg_rating?: number
          cities?: string[]
          created_at?: string
          description?: string
          duration?: string | null
          features?: string[] | null
          icon_name?: string
          id?: string
          includes?: string[]
          is_published?: boolean
          overview?: string | null
          price: string
          recovery?: string | null
          slug: string
          specialty_id?: string | null
          success_rate?: string | null
          tag?: string | null
          title: string
          total_patients?: string | null
        }
        Update: {
          available_hospitals?: string[] | null
          avg_rating?: number
          cities?: string[]
          created_at?: string
          description?: string
          duration?: string | null
          features?: string[] | null
          icon_name?: string
          id?: string
          includes?: string[]
          is_published?: boolean
          overview?: string | null
          price?: string
          recovery?: string | null
          slug?: string
          specialty_id?: string | null
          success_rate?: string | null
          tag?: string | null
          title?: string
          total_patients?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "packages_specialty_id_fkey"
            columns: ["specialty_id"]
            isOneToOne: false
            referencedRelation: "specialties"
            referencedColumns: ["id"]
          },
        ]
      }
      patient_cases: {
        Row: {
          case_code: string | null
          case_number: string
          case_stage: string
          closure_reason: string | null
          consultation_status: string
          coordinator_id: string | null
          created_at: string | null
          currency: string | null
          description: string | null
          discharge_status: string
          doctor_id: string | null
          document_status: string
          estimated_cost: number | null
          estimated_package_cost: number | null
          expected_treatment_date: string | null
          final_package_cost: number | null
          hospital_id: string | null
          id: string
          is_escalated: boolean
          lead_id: string | null
          notes: string | null
          outcome: string | null
          patient_id: string
          payment_status: string
          priority: string | null
          specialty_id: string | null
          status: Database["public"]["Enums"]["case_status"]
          title: string
          treatment_type: string | null
          updated_at: string | null
        }
        Insert: {
          case_code?: string | null
          case_number?: string
          case_stage?: string
          closure_reason?: string | null
          consultation_status?: string
          coordinator_id?: string | null
          created_at?: string | null
          currency?: string | null
          description?: string | null
          discharge_status?: string
          doctor_id?: string | null
          document_status?: string
          estimated_cost?: number | null
          estimated_package_cost?: number | null
          expected_treatment_date?: string | null
          final_package_cost?: number | null
          hospital_id?: string | null
          id?: string
          is_escalated?: boolean
          lead_id?: string | null
          notes?: string | null
          outcome?: string | null
          patient_id: string
          payment_status?: string
          priority?: string | null
          specialty_id?: string | null
          status?: Database["public"]["Enums"]["case_status"]
          title: string
          treatment_type?: string | null
          updated_at?: string | null
        }
        Update: {
          case_code?: string | null
          case_number?: string
          case_stage?: string
          closure_reason?: string | null
          consultation_status?: string
          coordinator_id?: string | null
          created_at?: string | null
          currency?: string | null
          description?: string | null
          discharge_status?: string
          doctor_id?: string | null
          document_status?: string
          estimated_cost?: number | null
          estimated_package_cost?: number | null
          expected_treatment_date?: string | null
          final_package_cost?: number | null
          hospital_id?: string | null
          id?: string
          is_escalated?: boolean
          lead_id?: string | null
          notes?: string | null
          outcome?: string | null
          patient_id?: string
          payment_status?: string
          priority?: string | null
          specialty_id?: string | null
          status?: Database["public"]["Enums"]["case_status"]
          title?: string
          treatment_type?: string | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "patient_cases_doctor_id_fkey"
            columns: ["doctor_id"]
            isOneToOne: false
            referencedRelation: "doctors"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "patient_cases_hospital_id_fkey"
            columns: ["hospital_id"]
            isOneToOne: false
            referencedRelation: "locations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "patient_cases_lead_id_fkey"
            columns: ["lead_id"]
            isOneToOne: false
            referencedRelation: "leads"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "patient_cases_specialty_id_fkey"
            columns: ["specialty_id"]
            isOneToOne: false
            referencedRelation: "specialties"
            referencedColumns: ["id"]
          },
        ]
      }
      patient_profiles: {
        Row: {
          address: string | null
          admission_date: string | null
          advance_paid: number | null
          age: number | null
          allergies: string | null
          anesthesia_consent: boolean | null
          blood_group: string | null
          case_id: string
          city: string | null
          coverage_amount: number | null
          created_at: string | null
          current_medications: string | null
          date_of_birth: string | null
          diagnosis: string | null
          email: string | null
          emergency_contact_name: string | null
          emergency_contact_number: string | null
          emergency_contact_relation: string | null
          estimated_surgery_date: string | null
          existing_conditions: string | null
          fasting_confirmation: boolean | null
          final_doctor_approval: boolean | null
          fitness_clearance: boolean | null
          full_name: string | null
          gender: string | null
          height_cm: number | null
          id: string
          id_number: string | null
          id_proof_path: string | null
          id_proof_type: string | null
          insurance_provider: string | null
          patient_photo_path: string | null
          payment_mode: string | null
          payment_type: string | null
          phone: string | null
          planned_procedure: string | null
          policy_number: string | null
          pregnancy_status: string | null
          preop_tests_status: string | null
          previous_surgeries: string | null
          privacy_consent: boolean | null
          procedure_type: string | null
          risk_disclosure: boolean | null
          room_category: string | null
          state: string | null
          surgery_consent: boolean | null
          updated_at: string | null
          weight_kg: number | null
        }
        Insert: {
          address?: string | null
          admission_date?: string | null
          advance_paid?: number | null
          age?: number | null
          allergies?: string | null
          anesthesia_consent?: boolean | null
          blood_group?: string | null
          case_id: string
          city?: string | null
          coverage_amount?: number | null
          created_at?: string | null
          current_medications?: string | null
          date_of_birth?: string | null
          diagnosis?: string | null
          email?: string | null
          emergency_contact_name?: string | null
          emergency_contact_number?: string | null
          emergency_contact_relation?: string | null
          estimated_surgery_date?: string | null
          existing_conditions?: string | null
          fasting_confirmation?: boolean | null
          final_doctor_approval?: boolean | null
          fitness_clearance?: boolean | null
          full_name?: string | null
          gender?: string | null
          height_cm?: number | null
          id?: string
          id_number?: string | null
          id_proof_path?: string | null
          id_proof_type?: string | null
          insurance_provider?: string | null
          patient_photo_path?: string | null
          payment_mode?: string | null
          payment_type?: string | null
          phone?: string | null
          planned_procedure?: string | null
          policy_number?: string | null
          pregnancy_status?: string | null
          preop_tests_status?: string | null
          previous_surgeries?: string | null
          privacy_consent?: boolean | null
          procedure_type?: string | null
          risk_disclosure?: boolean | null
          room_category?: string | null
          state?: string | null
          surgery_consent?: boolean | null
          updated_at?: string | null
          weight_kg?: number | null
        }
        Update: {
          address?: string | null
          admission_date?: string | null
          advance_paid?: number | null
          age?: number | null
          allergies?: string | null
          anesthesia_consent?: boolean | null
          blood_group?: string | null
          case_id?: string
          city?: string | null
          coverage_amount?: number | null
          created_at?: string | null
          current_medications?: string | null
          date_of_birth?: string | null
          diagnosis?: string | null
          email?: string | null
          emergency_contact_name?: string | null
          emergency_contact_number?: string | null
          emergency_contact_relation?: string | null
          estimated_surgery_date?: string | null
          existing_conditions?: string | null
          fasting_confirmation?: boolean | null
          final_doctor_approval?: boolean | null
          fitness_clearance?: boolean | null
          full_name?: string | null
          gender?: string | null
          height_cm?: number | null
          id?: string
          id_number?: string | null
          id_proof_path?: string | null
          id_proof_type?: string | null
          insurance_provider?: string | null
          patient_photo_path?: string | null
          payment_mode?: string | null
          payment_type?: string | null
          phone?: string | null
          planned_procedure?: string | null
          policy_number?: string | null
          pregnancy_status?: string | null
          preop_tests_status?: string | null
          previous_surgeries?: string | null
          privacy_consent?: boolean | null
          procedure_type?: string | null
          risk_disclosure?: boolean | null
          room_category?: string | null
          state?: string | null
          surgery_consent?: boolean | null
          updated_at?: string | null
          weight_kg?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "patient_profiles_case_id_fkey"
            columns: ["case_id"]
            isOneToOne: true
            referencedRelation: "patient_cases"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          address_line1: string | null
          address_line2: string | null
          allergies: string | null
          alternate_phone: string | null
          assigned_region: string | null
          avatar_url: string | null
          bio: string | null
          blood_group: string | null
          city: string | null
          country: string | null
          created_at: string | null
          date_of_birth: string | null
          department: string | null
          display_name: string | null
          doctor_id: string | null
          email: string | null
          emergency_contact_name: string | null
          emergency_contact_phone: string | null
          emergency_contact_relationship: string | null
          employee_id: string | null
          full_name: string | null
          gender: string | null
          hospital_id: string | null
          id: string
          insurance_number: string | null
          insurance_provider: string | null
          is_active: boolean
          medical_conditions: string | null
          notif_appointments: boolean
          notif_billing: boolean
          notif_case_updates: boolean
          notif_email: boolean
          notif_sms: boolean
          notif_whatsapp: boolean
          phone: string | null
          pincode: string | null
          role: string
          state: string | null
          updated_at: string | null
        }
        Insert: {
          address_line1?: string | null
          address_line2?: string | null
          allergies?: string | null
          alternate_phone?: string | null
          assigned_region?: string | null
          avatar_url?: string | null
          bio?: string | null
          blood_group?: string | null
          city?: string | null
          country?: string | null
          created_at?: string | null
          date_of_birth?: string | null
          department?: string | null
          display_name?: string | null
          doctor_id?: string | null
          email?: string | null
          emergency_contact_name?: string | null
          emergency_contact_phone?: string | null
          emergency_contact_relationship?: string | null
          employee_id?: string | null
          full_name?: string | null
          gender?: string | null
          hospital_id?: string | null
          id: string
          insurance_number?: string | null
          insurance_provider?: string | null
          is_active?: boolean
          medical_conditions?: string | null
          notif_appointments?: boolean
          notif_billing?: boolean
          notif_case_updates?: boolean
          notif_email?: boolean
          notif_sms?: boolean
          notif_whatsapp?: boolean
          phone?: string | null
          pincode?: string | null
          role?: string
          state?: string | null
          updated_at?: string | null
        }
        Update: {
          address_line1?: string | null
          address_line2?: string | null
          allergies?: string | null
          alternate_phone?: string | null
          assigned_region?: string | null
          avatar_url?: string | null
          bio?: string | null
          blood_group?: string | null
          city?: string | null
          country?: string | null
          created_at?: string | null
          date_of_birth?: string | null
          department?: string | null
          display_name?: string | null
          doctor_id?: string | null
          email?: string | null
          emergency_contact_name?: string | null
          emergency_contact_phone?: string | null
          emergency_contact_relationship?: string | null
          employee_id?: string | null
          full_name?: string | null
          gender?: string | null
          hospital_id?: string | null
          id?: string
          insurance_number?: string | null
          insurance_provider?: string | null
          is_active?: boolean
          medical_conditions?: string | null
          notif_appointments?: boolean
          notif_billing?: boolean
          notif_case_updates?: boolean
          notif_email?: boolean
          notif_sms?: boolean
          notif_whatsapp?: boolean
          phone?: string | null
          pincode?: string | null
          role?: string
          state?: string | null
          updated_at?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "profiles_doctor_id_fkey"
            columns: ["doctor_id"]
            isOneToOne: false
            referencedRelation: "doctors"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "profiles_hospital_id_fkey"
            columns: ["hospital_id"]
            isOneToOne: false
            referencedRelation: "locations"
            referencedColumns: ["id"]
          },
        ]
      }
      settlements: {
        Row: {
          amount: number
          case_id: string
          created_at: string
          created_by: string | null
          currency: string
          doctor_id: string | null
          hospital_id: string | null
          id: string
          notes: string | null
          payee_type: string
          payment_method: string | null
          payment_proof_path: string | null
          payment_reference: string | null
          reference_number: string | null
          settled_at: string | null
          settlement_percentage: number | null
          status: string
          updated_at: string
        }
        Insert: {
          amount?: number
          case_id: string
          created_at?: string
          created_by?: string | null
          currency?: string
          doctor_id?: string | null
          hospital_id?: string | null
          id?: string
          notes?: string | null
          payee_type: string
          payment_method?: string | null
          payment_proof_path?: string | null
          payment_reference?: string | null
          reference_number?: string | null
          settled_at?: string | null
          settlement_percentage?: number | null
          status?: string
          updated_at?: string
        }
        Update: {
          amount?: number
          case_id?: string
          created_at?: string
          created_by?: string | null
          currency?: string
          doctor_id?: string | null
          hospital_id?: string | null
          id?: string
          notes?: string | null
          payee_type?: string
          payment_method?: string | null
          payment_proof_path?: string | null
          payment_reference?: string | null
          reference_number?: string | null
          settled_at?: string | null
          settlement_percentage?: number | null
          status?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "settlements_case_id_fkey"
            columns: ["case_id"]
            isOneToOne: false
            referencedRelation: "patient_cases"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "settlements_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "settlements_doctor_id_fkey"
            columns: ["doctor_id"]
            isOneToOne: false
            referencedRelation: "doctors"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "settlements_hospital_id_fkey"
            columns: ["hospital_id"]
            isOneToOne: false
            referencedRelation: "locations"
            referencedColumns: ["id"]
          },
        ]
      }
      specialties: {
        Row: {
          created_at: string
          id: string
          name: string
          slug: string
          sort_order: number
        }
        Insert: {
          created_at?: string
          id?: string
          name: string
          slug: string
          sort_order?: number
        }
        Update: {
          created_at?: string
          id?: string
          name?: string
          slug?: string
          sort_order?: number
        }
        Relationships: []
      }
      states: {
        Row: {
          country_id: string
          created_at: string
          id: string
          name: string
        }
        Insert: {
          country_id: string
          created_at?: string
          id?: string
          name: string
        }
        Update: {
          country_id?: string
          created_at?: string
          id?: string
          name?: string
        }
        Relationships: [
          {
            foreignKeyName: "states_country_id_fkey"
            columns: ["country_id"]
            isOneToOne: false
            referencedRelation: "countries"
            referencedColumns: ["id"]
          },
        ]
      }
      user_roles: {
        Row: {
          id: string
          role: Database["public"]["Enums"]["app_role"]
          user_id: string
        }
        Insert: {
          id?: string
          role: Database["public"]["Enums"]["app_role"]
          user_id: string
        }
        Update: {
          id?: string
          role?: Database["public"]["Enums"]["app_role"]
          user_id?: string
        }
        Relationships: []
      }
      verification_audit_log: {
        Row: {
          action_at: string | null
          action_by: string | null
          action_reason: string | null
          id: string
          new_status: Database["public"]["Enums"]["verification_status"]
          notes: string | null
          previous_status:
            | Database["public"]["Enums"]["verification_status"]
            | null
          profile_id: string
          profile_type: string
        }
        Insert: {
          action_at?: string | null
          action_by?: string | null
          action_reason?: string | null
          id?: string
          new_status: Database["public"]["Enums"]["verification_status"]
          notes?: string | null
          previous_status?:
            | Database["public"]["Enums"]["verification_status"]
            | null
          profile_id: string
          profile_type: string
        }
        Update: {
          action_at?: string | null
          action_by?: string | null
          action_reason?: string | null
          id?: string
          new_status?: Database["public"]["Enums"]["verification_status"]
          notes?: string | null
          previous_status?:
            | Database["public"]["Enums"]["verification_status"]
            | null
          profile_id?: string
          profile_type?: string
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      generate_invoice_number: { Args: never; Returns: string }
      has_role: {
        Args: {
          _role: Database["public"]["Enums"]["app_role"]
          _user_id: string
        }
        Returns: boolean
      }
    }
    Enums: {
      app_role:
        | "admin"
        | "user"
        | "superadmin"
        | "coordinator"
        | "hospital"
        | "doctor"
        | "patient"
      case_status:
        | "new"
        | "assigned"
        | "in_progress"
        | "awaiting_docs"
        | "under_review"
        | "approved"
        | "rejected"
        | "completed"
        | "cancelled"
      verification_status:
        | "DRAFT"
        | "PENDING_VERIFICATION"
        | "UNDER_REVIEW"
        | "CHANGES_REQUESTED"
        | "APPROVED"
        | "REJECTED"
        | "SUSPENDED"
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {
      app_role: [
        "admin",
        "user",
        "superadmin",
        "coordinator",
        "hospital",
        "doctor",
        "patient",
      ],
      case_status: [
        "new",
        "assigned",
        "in_progress",
        "awaiting_docs",
        "under_review",
        "approved",
        "rejected",
        "completed",
        "cancelled",
      ],
      verification_status: [
        "DRAFT",
        "PENDING_VERIFICATION",
        "UNDER_REVIEW",
        "CHANGES_REQUESTED",
        "APPROVED",
        "REJECTED",
        "SUSPENDED",
      ],
    },
  },
} as const
